import type { Section } from "@features/learn/types";

export const sections: Section[] = [
    {
        id: "under_the_hood",
        icon: "IconAtom",
        title: "content.sections.under_the_hood",
        topics: [
            {
                id: "metro",
                icon: "IconTrain",
                title: "content.metro.title",
                subtitle: "content.metro.subtitle",
                body: [
                    { type: "heading", value: "content.metro.body.heading1" },
                    { type: "text", value: "content.metro.body.text1" },
                    { type: "text", value: "content.metro.body.text2" },
                    { type: "heading", value: "content.metro.body.heading2" },
                    { type: "text", value: "content.metro.body.text3" },
                    { type: "image", imagePath: require("./assets/metro_flow.png"), caption: "content.metro.body.image1" },
                ],
            },
            {
                id: "the_bridge",
                icon: "IconArrowsLeftRight",
                title: "content.the_bridge.title",
                subtitle: "content.the_bridge.subtitle",
                body: [
                    { type: "heading", value: "content.the_bridge.body.heading1" },
                    { type: "text", value: "content.the_bridge.body.text1" },
                    { type: "text", value: "content.the_bridge.body.text2" },
                    { type: "image", imagePath: require("./assets/bridge_architecture.png"), caption: "content.the_bridge.body.image1" },
                    { type: "heading", value: "content.the_bridge.body.heading2" },
                    { type: "text", value: "content.the_bridge.body.text3" },
                    { type: "image", imagePath: require("./assets/bridge_bottleneck.png"), caption: "content.the_bridge.body.image2" },
                ],
            },
            {
                id: "new_architecture",
                icon: "IconArrowIteration",
                title: "content.new_architecture.title",
                subtitle: "content.new_architecture.subtitle",
                body: [
                    { type: "heading", value: "content.new_architecture.body.heading1" },
                    { type: "text", value: "content.new_architecture.body.text1" },
                    { type: "text", value: "content.new_architecture.body.text2" },
                    { type: "heading", value: "content.new_architecture.body.heading2" },
                    { type: "text", value: "content.new_architecture.body.text3" },
                    { type: "image", imagePath: require("./assets/new_architecture_overview.png"), caption: "content.new_architecture.body.image1" },
                    { type: "heading", value: "content.new_architecture.body.heading3" },
                    { type: "text", value: "content.new_architecture.body.text4" },
                ],
            },
            {
                id: "jsi",
                icon: "IconPlugConnected",
                title: "content.jsi.title",
                subtitle: "content.jsi.subtitle",
                body: [
                    { type: "heading", value: "content.jsi.body.heading1" },
                    { type: "text", value: "content.jsi.body.text1" },
                    { type: "text", value: "content.jsi.body.text2" },
                    { type: "image", imagePath: require("./assets/jsi_comparison.png"), caption: "content.jsi.body.image1" },
                    { type: "heading", value: "content.jsi.body.heading2" },
                    { type: "text", value: "content.jsi.body.text3" },
                ],
            },
            {
                id: "fiber",
                icon: "IconHierarchy",
                title: "content.fiber.title",
                subtitle: "content.fiber.subtitle",
                body: [
                    { type: "heading", value: "content.fiber.body.heading1" },
                    { type: "text", value: "content.fiber.body.text1" },
                    { type: "text", value: "content.fiber.body.text2" },
                    { type: "image", imagePath: require("./assets/fiber_comparison.png"), caption: "content.fiber.body.image1" },
                    { type: "heading", value: "content.fiber.body.heading2" },
                    { type: "text", value: "content.fiber.body.text3" },
                ],
            },
            {
                id: "turbomodules",
                icon: "IconRocket",
                title: "content.turbomodules.title",
                subtitle: "content.turbomodules.subtitle",
                body: [
                    { type: "heading", value: "content.turbomodules.body.heading1" },
                    { type: "text", value: "content.turbomodules.body.text1" },
                    { type: "text", value: "content.turbomodules.body.text2" },
                    { type: "image", imagePath: require("./assets/turbomodules_loading.png"), caption: "content.turbomodules.body.image1" },
                    { type: "heading", value: "content.turbomodules.body.heading2" },
                    { type: "text", value: "content.turbomodules.body.text3" },
                    {
                        type: "code",
                        language: "typescript",
                        value: "import type { TurboModule } from \"react-native\";\nimport { TurboModuleRegistry } from \"react-native\";\n\nexport interface Spec extends TurboModule {\n  multiply(a: number, b: number): number;\n  getDeviceName(): Promise<string>;\n}\n\nexport default TurboModuleRegistry.getEnforcing<Spec>(\"MyModule\");",
                    },
                ],
            },
            {
                id: "fabric",
                icon: "IconLayersLinked",
                title: "content.fabric.title",
                subtitle: "content.fabric.subtitle",
                body: [
                    { type: "heading", value: "content.fabric.body.heading1" },
                    { type: "text", value: "content.fabric.body.text1" },
                    { type: "text", value: "content.fabric.body.text2" },
                    { type: "image", imagePath: require("./assets/fabric_renderer.png"), caption: "content.fabric.body.image1" },
                    { type: "heading", value: "content.fabric.body.heading2" },
                    { type: "text", value: "content.fabric.body.text3" },
                ],
            },
            {
                id: "codegen",
                icon: "IconCode",
                title: "content.codegen.title",
                subtitle: "content.codegen.subtitle",
                body: [
                    { type: "heading", value: "content.codegen.body.heading1" },
                    { type: "text", value: "content.codegen.body.text1" },
                    { type: "heading", value: "content.codegen.body.heading2" },
                    { type: "text", value: "content.codegen.body.text2" },
                    { type: "text", value: "content.codegen.body.text3" },
                    {
                        type: "code",
                        language: "typescript",
                        value: "// MyComponentNativeComponent.ts\nimport type { ViewProps } from 'react-native';\nimport type { HostComponent } from 'react-native';\nimport codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent';\n\ntype NativeProps = ViewProps & {\n  color?: string;\n};\n\nexport default codegenNativeComponent<NativeProps>('MyComponent') as HostComponent<NativeProps>;",
                    },
                ],
            },
        ],
    },
    {
        id: "layout",
        icon: "IconAdCircleOff",
        title: "content.sections.layout",
        topics: [
            {
                id: "flexbox_basics",
                icon: "IconLayoutGrid",
                title: "content.flexbox_basics.title",
                subtitle: "content.flexbox_basics.subtitle",
                body: [
                    { type: "heading", value: "content.flexbox_basics.body.heading1" },
                    { type: "text", value: "content.flexbox_basics.body.text1" },
                    { type: "text", value: "content.flexbox_basics.body.text2" },
                    {
                        type: "code",
                        language: "tsx",
                        value: "import { View, StyleSheet } from \"react-native\";\n\nexport function CenteredLayout() {\n  return (\n    <View style={styles.container}>\n      <View style={styles.box} />\n    </View>\n  );\n}\n\nconst styles = StyleSheet.create({\n  container: {\n    flex: 1,\n    justifyContent: \"center\",\n    alignItems: \"center\",\n  },\n  box: {\n    width: 80,\n    height: 80,\n    backgroundColor: \"#67e8f9\",\n  },\n});",
                    },
                    { type: "heading", value: "content.flexbox_basics.body.heading2" },
                    { type: "text", value: "content.flexbox_basics.body.text3" },
                ],
            },
            {
                id: "position_absolute",
                icon: "IconStack2",
                title: "content.position_absolute.title",
                subtitle: "content.position_absolute.subtitle",
                body: [
                    { type: "heading", value: "content.position_absolute.body.heading1" },
                    { type: "text", value: "content.position_absolute.body.text1" },
                    { type: "text", value: "content.position_absolute.body.text2" },
                    { type: "heading", value: "content.position_absolute.body.heading2" },
                    { type: "text", value: "content.position_absolute.body.text3" },
                    {
                        type: "code",
                        language: "typescript",
                        value: "import { View } from \"react-native\";\n\nexport function BadgeExample() {\n  return (\n    <View style={{ width: 48, height: 48 }}>\n      <View\n        style={{ flex: 1, backgroundColor: \"#6366f1\", borderRadius: 8 }}\n      />\n      <View\n        style={{\n          position: \"absolute\",\n          top: -4,\n          right: -4,\n          width: 16,\n          height: 16,\n          borderRadius: 8,\n          backgroundColor: \"#ef4444\",\n        }}\n      />\n    </View>\n  );\n}",
                    },
                    { type: "heading", value: "content.position_absolute.body.heading3" },
                    { type: "text", value: "content.position_absolute.body.text4" },
                ],
            },
            {
                id: "dimensions",
                icon: "IconRuler",
                title: "content.dimensions.title",
                subtitle: "content.dimensions.subtitle",
                body: [
                    { type: "heading", value: "content.dimensions.body.heading1" },
                    { type: "text", value: "content.dimensions.body.text1" },
                    { type: "heading", value: "content.dimensions.body.heading2" },
                    { type: "text", value: "content.dimensions.body.text2" },
                    {
                        type: "code",
                        language: "typescript",
                        value: "import { Dimensions } from \"react-native\";\n\nconst { width, height } = Dimensions.get(\"window\");",
                    },
                    { type: "heading", value: "content.dimensions.body.heading3" },
                    { type: "text", value: "content.dimensions.body.text3" },
                    {
                        type: "code",
                        language: "typescript",
                        value: "import { useWindowDimensions, View } from \"react-native\";\n\nexport function ResponsiveLayout() {\n  const { width, height } = useWindowDimensions();\n  const isLandscape = width > height;\n\n  return (\n    <View\n      style={{\n        flex: 1,\n        flexDirection: isLandscape ? \"row\" : \"column\",\n      }}\n    />\n  );\n}",
                    },
                ],
            },
        ],
    },
    {
        id: "performance",
        icon: "IconGauge",
        title: "content.sections.performance",
        topics: [
            {
                id: "js_thread_ui_thread",
                icon: "IconCpu",
                title: "content.js_thread_ui_thread.title",
                subtitle: "content.js_thread_ui_thread.subtitle",
                body: [
                    { type: "heading", value: "content.js_thread_ui_thread.body.heading1" },
                    { type: "text", value: "content.js_thread_ui_thread.body.text1" },
                    { type: "text", value: "content.js_thread_ui_thread.body.text2" },
                    { type: "image", imagePath: require("./assets/js_ui_threads.png"), caption: "content.js_thread_ui_thread.body.image1" },
                    { type: "heading", value: "content.js_thread_ui_thread.body.heading2" },
                    { type: "text", value: "content.js_thread_ui_thread.body.text3" },
                ],
            },
            {
                id: "hermes_engine",
                icon: "IconFlame",
                title: "content.hermes_engine.title",
                subtitle: "content.hermes_engine.subtitle",
                body: [
                    { type: "heading", value: "content.hermes_engine.body.heading1" },
                    { type: "text", value: "content.hermes_engine.body.text1" },
                    { type: "heading", value: "content.hermes_engine.body.heading2" },
                    { type: "text", value: "content.hermes_engine.body.text2" },
                    { type: "text", value: "content.hermes_engine.body.text3" },
                    {
                        type: "code",
                        language: "typescript",
                        value: "const isHermes = () => !!(global as any).HermesInternal;\nconsole.log(\"Hermes:\", isHermes());",
                    },
                ],
            },
            {
                id: "flatlist_optimization",
                icon: "IconList",
                title: "content.flatlist_optimization.title",
                subtitle: "content.flatlist_optimization.subtitle",
                body: [
                    { type: "heading", value: "content.flatlist_optimization.body.heading1" },
                    { type: "text", value: "content.flatlist_optimization.body.text1" },
                    { type: "heading", value: "content.flatlist_optimization.body.heading2" },
                    { type: "text", value: "content.flatlist_optimization.body.text2" },
                    { type: "text", value: "content.flatlist_optimization.body.text4" },
                    {
                        type: "code",
                        language: "typescript",
                        value: "const [selectedId, setSelectedId] = useState<string | null>(null);\n\n<FlatList\n  data={items}\n  keyExtractor={(item) => item.id}\n  extraData={selectedId}\n  renderItem={({ item }) => (\n    <ItemRow\n      title={item.title}\n      selected={item.id === selectedId}\n      onPress={() => setSelectedId(item.id)}\n    />\n  )}\n/>",
                    },
                    { type: "heading", value: "content.flatlist_optimization.body.heading3" },
                    { type: "text", value: "content.flatlist_optimization.body.text3" },
                    {
                        type: "code",
                        language: "typescript",
                        value: "import { FlatList, Text } from \"react-native\";\nimport React, { useCallback } from \"react\";\n\nconst ItemRow = React.memo(({ title }: { title: string }) => (\n  <Text>{title}</Text>\n));\n\nexport function MyList({ data }: { data: { id: string; title: string }[] }) {\n  const renderItem = useCallback(\n    ({ item }: { item: { id: string; title: string } }) => (\n      <ItemRow title={item.title} />\n    ),\n    []\n  );\n\n  return (\n    <FlatList\n      data={data}\n      keyExtractor={(item) => item.id}\n      renderItem={renderItem}\n    />\n  );\n}",
                    },
                ],
            },
            {
                id: "usememo_usecallback",
                icon: "IconBolt",
                title: "content.usememo_usecallback.title",
                subtitle: "content.usememo_usecallback.subtitle",
                body: [
                    { type: "heading", value: "content.usememo_usecallback.body.heading1" },
                    { type: "text", value: "content.usememo_usecallback.body.text1" },
                    { type: "heading", value: "content.usememo_usecallback.body.heading2" },
                    { type: "text", value: "content.usememo_usecallback.body.text2" },
                    {
                        type: "code",
                        language: "typescript",
                        value: "const sorted = useMemo(\n  () => [...items].sort((a, b) => a.name.localeCompare(b.name)),\n  [items]\n);",
                    },
                    { type: "heading", value: "content.usememo_usecallback.body.heading3" },
                    { type: "text", value: "content.usememo_usecallback.body.text3" },
                    {
                        type: "code",
                        language: "typescript",
                        value: "const handlePress = useCallback((id: string) => {\n  dispatch({ type: \"SELECT\", id });\n}, [dispatch]);",
                    },
                ],
            },
        ],
    },
    {
        id: "debugging",
        icon: "IconBug",
        title: "content.sections.debugging",
        topics: [
            {
                id: "react_native_devtools",
                icon: "IconDeviceLaptop",
                title: "content.react_native_devtools.title",
                subtitle: "content.react_native_devtools.subtitle",
                body: [
                    { type: "heading", value: "content.react_native_devtools.body.heading1" },
                    { type: "text", value: "content.react_native_devtools.body.text1" },
                    { type: "heading", value: "content.react_native_devtools.body.heading2" },
                    { type: "text", value: "content.react_native_devtools.body.text2" },
                    { type: "text", value: "content.react_native_devtools.body.text3" },
                    { type: "image", imagePath: require("./assets/print_devtools.png"), caption: "content.react_native_devtools.body.image1" },
                ],
            },
            {
                id: "performance_monitor",
                icon: "IconChartLine",
                title: "content.performance_monitor.title",
                subtitle: "content.performance_monitor.subtitle",
                body: [
                    { type: "heading", value: "content.performance_monitor.body.heading1" },
                    { type: "text", value: "content.performance_monitor.body.text1" },
                    { type: "heading", value: "content.performance_monitor.body.heading2" },
                    { type: "text", value: "content.performance_monitor.body.text2" },
                    { type: "text", value: "content.performance_monitor.body.text3" },
                    { type: "image", imagePath: require("./assets/print_performance_monitor.png"), caption: "content.performance_monitor.body.image1" },
                ],
            },
            {
                id: "profiler",
                icon: "IconActivity",
                title: "content.profiler.title",
                subtitle: "content.profiler.subtitle",
                body: [
                    { type: "heading", value: "content.profiler.body.heading1" },
                    { type: "text", value: "content.profiler.body.text1" },
                    { type: "heading", value: "content.profiler.body.heading2" },
                    { type: "text", value: "content.profiler.body.text2" },
                    { type: "text", value: "content.profiler.body.text3" },
                    { type: "image", imagePath: require("./assets/print_profiler.png"), caption: "content.profiler.body.image1" },
                ],
            },
            {
                id: "logbox",
                icon: "IconAlertTriangle",
                title: "content.logbox.title",
                subtitle: "content.logbox.subtitle",
                body: [
                    { type: "heading", value: "content.logbox.body.heading1" },
                    { type: "text", value: "content.logbox.body.text1" },
                    { type: "heading", value: "content.logbox.body.heading2" },
                    { type: "text", value: "content.logbox.body.text2" },
                    { type: "text", value: "content.logbox.body.text3" },
                    {
                        type: "code",
                        language: "typescript",
                        value: "import { LogBox } from \"react-native\";\n\nLogBox.ignoreLogs([\n  \"VirtualizedLists should never be nested\",\n  /Warning: componentWillReceiveProps/,\n]);",
                    },
                    { type: "image", imagePath: require("./assets/print_logbox.png"), caption: "content.logbox.body.image1" },
                ],
            },
            {
                id: "sourcemaps",
                icon: "IconMap2",
                title: "content.sourcemaps.title",
                subtitle: "content.sourcemaps.subtitle",
                body: [
                    { type: "heading", value: "content.sourcemaps.body.heading1" },
                    { type: "text", value: "content.sourcemaps.body.text1" },
                    { type: "heading", value: "content.sourcemaps.body.heading2" },
                    { type: "text", value: "content.sourcemaps.body.text2" },
                    { type: "text", value: "content.sourcemaps.body.text3" },
                ],
            },
            {
                id: "native_debugging",
                icon: "IconTerminal2",
                title: "content.native_debugging.title",
                subtitle: "content.native_debugging.subtitle",
                body: [
                    { type: "heading", value: "content.native_debugging.body.heading1" },
                    { type: "text", value: "content.native_debugging.body.text1" },
                    {
                        type: "code",
                        language: "typescript",
                        value: "# stream logs tagged ReactNative and ReactNativeJS\nadb logcat ReactNative:V ReactNativeJS:V *:S\n\n# stream all logs from a specific package\nadb logcat --pid=$(adb shell pidof -s com.yourapp)",
                    },
                    { type: "text", value: "content.native_debugging.body.text2" },
                    { type: "heading", value: "content.native_debugging.body.heading2" },
                    { type: "text", value: "content.native_debugging.body.text3" },
                    { type: "text", value: "content.native_debugging.body.text4" },
                    { type: "heading", value: "content.native_debugging.body.heading3" },
                    { type: "text", value: "content.native_debugging.body.text5" },
                ],
            },
        ],
    },
    {
        id: "accessibility",
        icon: "IconAccessible",
        title: "content.sections.accessibility",
        topics: [
            {
                id: "accessibility_labels",
                icon: "IconTag",
                title: "content.accessibility_labels.title",
                subtitle: "content.accessibility_labels.subtitle",
                body: [
                    { type: "heading", value: "content.accessibility_labels.body.heading1" },
                    { type: "text", value: "content.accessibility_labels.body.text1" },
                    { type: "heading", value: "content.accessibility_labels.body.heading2" },
                    { type: "text", value: "content.accessibility_labels.body.text2" },
                    { type: "heading", value: "content.accessibility_labels.body.heading3" },
                    { type: "text", value: "content.accessibility_labels.body.text3" },
                ],
            },
            {
                id: "accessibility_info",
                icon: "IconInfoCircle",
                title: "content.accessibility_info.title",
                subtitle: "content.accessibility_info.subtitle",
                body: [
                    { type: "heading", value: "content.accessibility_info.body.heading1" },
                    { type: "text", value: "content.accessibility_info.body.text1" },
                    { type: "heading", value: "content.accessibility_info.body.heading2" },
                    { type: "text", value: "content.accessibility_info.body.text2" },
                    { type: "text", value: "content.accessibility_info.body.text3" },
                    {
                        type: "code",
                        language: "typescript",
                        value: "import { AccessibilityInfo } from \"react-native\";\nimport { useEffect } from \"react\";\n\nuseEffect(() => {\n  AccessibilityInfo.isScreenReaderEnabled().then((enabled) => {\n    if (enabled) {\n      AccessibilityInfo.announceForAccessibility(\"List loaded with 24 items\");\n    }\n  });\n}, []);",
                    },
                ],
            },
            {
                id: "focus_order",
                icon: "IconSortAscending",
                title: "content.focus_order.title",
                subtitle: "content.focus_order.subtitle",
                body: [
                    { type: "heading", value: "content.focus_order.body.heading1" },
                    { type: "text", value: "content.focus_order.body.text1" },
                    { type: "heading", value: "content.focus_order.body.heading2" },
                    { type: "text", value: "content.focus_order.body.text2" },
                    { type: "heading", value: "content.focus_order.body.heading3" },
                    { type: "text", value: "content.focus_order.body.text3" },
                ],
            },
            {
                id: "voiceover_talkback",
                icon: "IconEar",
                title: "content.voiceover_talkback.title",
                subtitle: "content.voiceover_talkback.subtitle",
                body: [
                    { type: "heading", value: "content.voiceover_talkback.body.heading1" },
                    { type: "text", value: "content.voiceover_talkback.body.text1" },
                    { type: "heading", value: "content.voiceover_talkback.body.heading2" },
                    { type: "text", value: "content.voiceover_talkback.body.text2" },
                    { type: "heading", value: "content.voiceover_talkback.body.heading3" },
                    { type: "text", value: "content.voiceover_talkback.body.text3" },
                ],
            },
        ],
    },
    {
        id: "android",
        icon: "IconBrandAndroid",
        title: "content.sections.android",
        topics: [
            {
                id: "android_sdk",
                icon: "IconPackages",
                title: "content.android_sdk.title",
                subtitle: "content.android_sdk.subtitle",
                body: [
                    { type: "heading", value: "content.android_sdk.body.heading1" },
                    { type: "text", value: "content.android_sdk.body.text1" },
                    { type: "heading", value: "content.android_sdk.body.heading2" },
                    { type: "text", value: "content.android_sdk.body.text2" },
                    { type: "text", value: "content.android_sdk.body.text3" },
                ],
            },
            {
                id: "jdk_build_tools",
                icon: "IconCoffee",
                title: "content.jdk_build_tools.title",
                subtitle: "content.jdk_build_tools.subtitle",
                body: [
                    { type: "heading", value: "content.jdk_build_tools.body.heading1" },
                    { type: "text", value: "content.jdk_build_tools.body.text1" },
                    { type: "heading", value: "content.jdk_build_tools.body.heading2" },
                    { type: "text", value: "content.jdk_build_tools.body.text2" },
                    { type: "text", value: "content.jdk_build_tools.body.text3" },
                ],
            },
            {
                id: "gradle_gradlew",
                icon: "IconTools",
                title: "content.gradle_gradlew.title",
                subtitle: "content.gradle_gradlew.subtitle",
                body: [
                    { type: "heading", value: "content.gradle_gradlew.body.heading1" },
                    { type: "text", value: "content.gradle_gradlew.body.text1" },
                    { type: "heading", value: "content.gradle_gradlew.body.heading2" },
                    { type: "text", value: "content.gradle_gradlew.body.text2" },
                    { type: "text", value: "content.gradle_gradlew.body.text3" },
                    {
                        type: "code",
                        language: "typescript",
                        value: "# build and install debug APK\n./gradlew installDebug\n\n# build release APK\n./gradlew assembleRelease\n\n# wipe build output\n./gradlew clean\n\n# stop the Gradle daemon\n./gradlew --stop",
                    },
                ],
            },
            {
                id: "android_manifest",
                icon: "IconFileDescription",
                title: "content.android_manifest.title",
                subtitle: "content.android_manifest.subtitle",
                body: [
                    { type: "heading", value: "content.android_manifest.body.heading1" },
                    { type: "text", value: "content.android_manifest.body.text1" },
                    { type: "heading", value: "content.android_manifest.body.heading2" },
                    { type: "text", value: "content.android_manifest.body.text2" },
                    { type: "text", value: "content.android_manifest.body.text3" },
                    {
                        type: "code",
                        language: "xml",
                        value: "<uses-permission android:name=\"android.permission.INTERNET\" />\n<uses-permission android:name=\"android.permission.CAMERA\" />\n<uses-permission android:name=\"android.permission.ACCESS_FINE_LOCATION\" />",
                    },
                ],
            },
            {
                id: "android_api_levels",
                icon: "IconVersions",
                title: "content.android_api_levels.title",
                subtitle: "content.android_api_levels.subtitle",
                body: [
                    { type: "heading", value: "content.android_api_levels.body.heading1" },
                    { type: "text", value: "content.android_api_levels.body.text1" },
                    { type: "heading", value: "content.android_api_levels.body.heading2" },
                    { type: "text", value: "content.android_api_levels.body.text2" },
                    { type: "text", value: "content.android_api_levels.body.text3" },
                ],
            },
        ],
    },
    {
        id: "ios",
        icon: "IconBrandApple",
        title: "content.sections.ios",
        topics: [
            {
                id: "xcode_simulator",
                icon: "IconDeviceMobile",
                title: "content.xcode_simulator.title",
                subtitle: "content.xcode_simulator.subtitle",
                body: [
                    { type: "heading", value: "content.xcode_simulator.body.heading1" },
                    { type: "text", value: "content.xcode_simulator.body.text1" },
                    { type: "heading", value: "content.xcode_simulator.body.heading2" },
                    { type: "text", value: "content.xcode_simulator.body.text2" },
                    { type: "text", value: "content.xcode_simulator.body.text3" },
                ],
            },
            {
                id: "cocoapods",
                icon: "IconPackage",
                title: "content.cocoapods.title",
                subtitle: "content.cocoapods.subtitle",
                body: [
                    { type: "heading", value: "content.cocoapods.body.heading1" },
                    { type: "text", value: "content.cocoapods.body.text1" },
                    { type: "heading", value: "content.cocoapods.body.heading2" },
                    { type: "text", value: "content.cocoapods.body.text2" },
                    { type: "text", value: "content.cocoapods.body.text3" },
                ],
            },
            {
                id: "info_plist",
                icon: "IconFileDescription",
                title: "content.info_plist.title",
                subtitle: "content.info_plist.subtitle",
                body: [
                    { type: "heading", value: "content.info_plist.body.heading1" },
                    { type: "text", value: "content.info_plist.body.text1" },
                    { type: "heading", value: "content.info_plist.body.heading2" },
                    { type: "text", value: "content.info_plist.body.text2" },
                    { type: "text", value: "content.info_plist.body.text3" },
                ],
            },
            {
                id: "app_sandbox",
                icon: "IconShieldLock",
                title: "content.app_sandbox.title",
                subtitle: "content.app_sandbox.subtitle",
                body: [
                    { type: "heading", value: "content.app_sandbox.body.heading1" },
                    { type: "text", value: "content.app_sandbox.body.text1" },
                    { type: "heading", value: "content.app_sandbox.body.heading2" },
                    { type: "text", value: "content.app_sandbox.body.text2" },
                    { type: "text", value: "content.app_sandbox.body.text3" },
                ],
            },
            {
                id: "ios_sdk_deployment",
                icon: "IconVersions",
                title: "content.ios_sdk_deployment.title",
                subtitle: "content.ios_sdk_deployment.subtitle",
                body: [
                    { type: "heading", value: "content.ios_sdk_deployment.body.heading1" },
                    { type: "text", value: "content.ios_sdk_deployment.body.text1" },
                    { type: "heading", value: "content.ios_sdk_deployment.body.heading2" },
                    { type: "text", value: "content.ios_sdk_deployment.body.text2" },
                    { type: "text", value: "content.ios_sdk_deployment.body.text3" },
                ],
            },
        ],
    },
    {
        id: "publishing",
        icon: "IconRocket",
        title: "content.sections.publishing",
        topics: [
            {
                id: "signing_certificates",
                icon: "IconCertificate",
                title: "content.signing_certificates.title",
                subtitle: "content.signing_certificates.subtitle",
                body: [
                    { type: "heading", value: "content.signing_certificates.body.heading1" },
                    { type: "text", value: "content.signing_certificates.body.text1" },
                    { type: "heading", value: "content.signing_certificates.body.heading2" },
                    { type: "text", value: "content.signing_certificates.body.text2" },
                    { type: "heading", value: "content.signing_certificates.body.heading3" },
                    { type: "text", value: "content.signing_certificates.body.text3" },
                ],
            },
            {
                id: "app_store_connect",
                icon: "IconBrandAppstore",
                title: "content.app_store_connect.title",
                subtitle: "content.app_store_connect.subtitle",
                body: [
                    { type: "heading", value: "content.app_store_connect.body.heading1" },
                    { type: "text", value: "content.app_store_connect.body.text1" },
                    { type: "heading", value: "content.app_store_connect.body.heading2" },
                    { type: "text", value: "content.app_store_connect.body.text2" },
                    { type: "heading", value: "content.app_store_connect.body.heading3" },
                    { type: "text", value: "content.app_store_connect.body.text3" },
                ],
            },
            {
                id: "google_play_console",
                icon: "IconBrandGooglePlay",
                title: "content.google_play_console.title",
                subtitle: "content.google_play_console.subtitle",
                body: [
                    { type: "heading", value: "content.google_play_console.body.heading1" },
                    { type: "text", value: "content.google_play_console.body.text1" },
                    { type: "heading", value: "content.google_play_console.body.heading2" },
                    { type: "text", value: "content.google_play_console.body.text2" },
                    { type: "heading", value: "content.google_play_console.body.heading3" },
                    { type: "text", value: "content.google_play_console.body.text3" },
                ],
            },
            {
                id: "ota_updates",
                icon: "IconCloudUpload",
                title: "content.ota_updates.title",
                subtitle: "content.ota_updates.subtitle",
                body: [
                    { type: "heading", value: "content.ota_updates.body.heading1" },
                    { type: "text", value: "content.ota_updates.body.text1" },
                    { type: "heading", value: "content.ota_updates.body.heading2" },
                    { type: "text", value: "content.ota_updates.body.text2" },
                    { type: "heading", value: "content.ota_updates.body.heading3" },
                    { type: "text", value: "content.ota_updates.body.text3" },
                ],
            },
        ],
    },
];
